"""empty message

Revision ID: 15fa4784ccfb
Revises: 7d46ad917b09
Create Date: 2016-10-04 23:12:10.677590

"""

# revision identifiers, used by Alembic.
revision = '15fa4784ccfb'
down_revision = '7d46ad917b09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('avail_type', sa.Unicode(length=50), nullable=True))
    op.add_column('address', sa.Column('photo_url', sa.Unicode(length=300), nullable=True))
    op.add_column('address', sa.Column('spot_type', sa.Unicode(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.Unicode(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('address', 'spot_type')
    op.drop_column('address', 'photo_url')
    op.drop_column('address', 'avail_type')
    ### end Alembic commands ###
