"""empty message

Revision ID: e049876634fa
Revises: 15fa4784ccfb
Create Date: 2016-10-08 18:37:12.222658

"""

# revision identifiers, used by Alembic.
revision = 'e049876634fa'
down_revision = '15fa4784ccfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address_index', table_name='address')
    op.drop_index('distance', table_name='address')
    op.create_index(op.f('ix_address_distance_address_a_id'), 'address_distance', ['address_a_id'], unique=False)
    op.create_index(op.f('ix_address_distance_address_b_id'), 'address_distance', ['address_b_id'], unique=False)
    op.create_index(op.f('ix_address_distance_mapbox_response'), 'address_distance', ['mapbox_response'], unique=False)
    op.create_index(op.f('ix_address_distance_speed_scala'), 'address_distance', ['speed_scala'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_distance_speed_scala'), table_name='address_distance')
    op.drop_index(op.f('ix_address_distance_mapbox_response'), table_name='address_distance')
    op.drop_index(op.f('ix_address_distance_address_b_id'), table_name='address_distance')
    op.drop_index(op.f('ix_address_distance_address_a_id'), table_name='address_distance')
    op.create_index('distance', 'address', ['id', 'user_id', 'latitude', 'longitude', 'mapbox_place_name', 'street_name', 'street_number', 'building_number', 'cross_street', 'suite_number', 'neighborhood', 'district', 'county', 'country', 'provence', 'phone', 'state', 'postal_code', 'name', 'details', 'price', 'is_dest', 'is_avail', 'avail_type', 'photo_url', 'spot_type'], unique=False)
    op.create_index('address_index', 'address', ['id', 'user_id', 'latitude', 'longitude', 'mapbox_place_name', 'street_name', 'street_number', 'building_number', 'cross_street', 'suite_number', 'neighborhood', 'district', 'county', 'country', 'provence', 'phone', 'state', 'postal_code', 'name', 'details', 'price', 'is_dest', 'is_avail', 'avail_type', 'photo_url', 'spot_type'], unique=False)
    ### end Alembic commands ###
